const fs = require('fs');
const { stripIndent } = require('common-tags');

const readmePath = './README.md';

/**
 * @typedef {import('./libraries-schema.js').GameMakerLibraryData} Libraries
 */

/**
 * @param {Libraries} libraries
 */
function compileReadme(libraries) {
  /**
   * The "preamble" was taken directly from the original README.md file.
   * It now includes a comment informing users who open up the README file
   * that they should not edit it directly, but should instead edit it
   * here.
   *
   * In other words, ignore that comment telling you not to edit,
   * **if you are doing your editing right here in this file**.
   *
   * @type {string}
   */
  const preamble = stripIndent(`
    <!--
      DO NOT EDIT. This file is automatically generated,
      so any manual edits will be lost. To change the README
      content, edit the \`compileReadme\` function in \`utility/compile.js\`.
    -->
    <h1 align="center">${libraries.title}</h1>

    <p align="center">${libraries.description}</p>

    <p align="center">
      Come chat about GameMaker on the <a href="https://discord.gg/8krYCqr">Discord server</a>
    </p>`);

  let markdownComponents = [
    preamble,
    '## Contributing',
    stripIndent`
      To add or edit information about a GameMaker library,
      see the [Contributing Guide](./CONTRIBUTING.md).
    `,
    '## Libraries',
    ...libraries.libraries.map((library) => {
      // NOTE: This is currently just re-creating the original markdown
      //       but it could be changed to add tags, authors, and any other
      //       information that gets added.
      return `[${library.title}](${library.url})`;
    }),
  ];
  fs.writeFileSync(readmePath, markdownComponents.join('\n\n'));
}
exports.compileReadme = compileReadme;
